ikuai-url: https://192.168.0.1
username: admin
password: ""
ikuai-url-ignore-cert: true
cron: "0 7 * * *"
mode: ipgroup
next-hop-gateway: "192.168.0.2"
custom-lan-ip: "192.168.0.3-192.168.0.254"

ip-group:
  - tag: Telegram
    url: https://raw.githubusercontent.com/Loyalsoldier/geoip/release/text/telegram.txt

stream-ipport:
  - type: "1"
    opt-tagname: "负责分流到下一跳"
    interface: ""
    nexthop: "192.168.0.2"
    src-addr: "192.168.0.3-192.168.0.254"
    dst-addr: "198.18.0.0-198.19.255.255"
    ip-group: "Telegram"
    dst-addr-inv: 0
    prio: 0
    protocol: "tcp+udp"

webui:
  enable: true
  port: 19001
  user: admin
  pass: ""
  cdn-prefix: https://cdn.jsdelivr.net/npm
